### ISSUE TITLE
Any potential support for a Windows version?

### ISSUE THREAD

**Issue by djD-REK** [wbyoung/avn#102]
Hey, I'd like to use this tool on Windows, but it seems hard-coded to *nix.

I use nvm-windows for node version management (Windows 10).

```
C:\dev
λ npm install -g avn
C:\Program Files\nodejs\avn -> C:\Program Files\nodejs\node_modules\avn\bin-public\avn
+ avn@0.2.4
added 282 packages from 548 contributors in 28.103s

C:\dev
λ npm install -g avn-nvm
Terminate batch job (Y/N)? y

C:\dev
λ npm install -g avn-nvm
npm WARN avn-nvm@0.2.2 requires a peer of avn@0.2.x but none is installed. You must install peer dependencies yourself.

+ avn-nvm@0.2.2
added 14 packages from 8 contributors in 2.16s

C:\dev
λ avn setup
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/cp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by wbyoung** [comment]
PR welcome.
