### ISSUE TITLE
fatal error on macOS w bash

### ISSUE THREAD

**Issue by darkn3rd** [wbyoung/avn#124]
When I try to source avn with `. ~/.avn/bin/avn.sh`, I get the following error:

```
Fatal Error: Cannot find module '/Users/someuser/.avn/plugins/avn-nvm'
Require stack:
- /Users/someuser/.avn/lib/plugins.js
- /Users/someuser/.avn/lib/hooks.js
- /Users/someuser/.avn/lib/avn.js
- /Users/someuser/.avn/index.js
- /Users/someuser/.avn/bin/_avn
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/someuser/.avn/lib/plugins.js:59:20
    at tryCatcher (/Users/someuser/.avn/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/someuser/.avn/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/Users/someuser/.avn/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/someuser/.avn/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/someuser/.avn/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/someuser/.avn/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/someuser/.avn/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/someuser/.avn/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/someuser/.avn/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/someuser/.avn/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/someuser/.avn/node_modules/bluebird/js/release/async.js:15:14)
```

My steps:

1. `npm install -g avn avn-nvm avn-n`
2 `avn setup` which adds config to `$HOME/.zshrc` despite current shell as bash
3. add same configuration to `$HOME/.bashrc` and launch new terminal tab
4. cd to project with `.node-version`, version doesn't change
5. attempt to source in current shell directly with `. ~/.avn/bin/avn.sh` and get a fatal error. 

**Details**

- _avn_ `avn --version`: `0.2.4`
- _node_ `node --version`: `v18.4.0`
- _nvm_ `nvm --version`: `0.39.3`
- _n_ `n --version`: n/a
- _zsh_ `zsh --version`: `zsh 5.9 (arm-apple-darwin21.3.0)`
- _bash_ `bash --version`: `GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin21.6.0)`

The output of `__avn_debug` in the directory with a `.node-version` file is:

```sh
# n/a as do not get this far
```

`avn` is loaded in my `~/.{bash|zsh}{_profile|rc}` file with:
```bash
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
```

**nvm specific**

- [ ] As an `nvm` user I am confirming that I did _not_ install with Homebrew

**Comment by wbyoung** [comment]
Try reinstalling.

```
rm -R ~/.avn
```

Then [install](https://github.com/wbyoung/avn#install).

FYI: I don't use this or really work on this project any more.
