### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by robertmarkbram** [wbyoung/avn#90]
Please describe your issue clearly and also include all details below.

**Details**

- _avn_ `0.2.4`
- _node_ `v13.3.0`
- _nvm_ `1.1.7`
- _n_ `n/a`
- _zsh_ `n/a`
- _bash_ `n/a`
- Using PowerShell

When trying to install:

```
PS C:\WINDOWS\system32> npm install -g avn avn-nvm avn-n
C:\Program Files\nodejs\avn -> C:\Program Files\nodejs\node_modules\avn\bin-public\avn
+ avn@0.2.4
+ avn-nvm@0.2.2
+ avn-n@0.2.0
added 299 packages from 549 contributors in 14.97s
PS C:\WINDOWS\system32> avn setup
avn: profile already set up (~/.bash_profile)
events.js:196
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/cp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn /bin/cp',
  path: '/bin/cp',
  spawnargs: [
    '-RL',
    'C:\\AppsNoSpace\\nvm\\v13.3.0\\node_modules\\avn/',
    'C:\\Users\\Robert Bram\\.avn'
  ]
}
PS C:\WINDOWS\system32>
```

- [ ] As an `nvm` user I am confirming that I did _not_ install with Homebrew

**Comment by wbyoung** [comment]
Windows isn't supposed. Feel free to try to get things working and open a PR, though.
