### ISSUE TITLE
Documentation .avnrc

### ISSUE THREAD

**Issue by Janaka-Steph** [wbyoung/avn#94]
Hello,

I can't find any documentation on how to fill the .avnrc
I would like to force avn to use avn-n instead of anv-nvm, because I got this error:
```
Fatal Error: Cannot find module '/Users/steph/.avn/plugins/avn-nvm'
Require stack:
- /Users/steph/.avn/lib/plugins.js
- /Users/steph/.avn/lib/hooks.js
- /Users/steph/.avn/lib/avn.js
- /Users/steph/.avn/index.js
- /Users/steph/.avn/bin/_avn
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/steph/.avn/lib/plugins.js:59:20
    at tryCatcher (/Users/steph/.avn/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/steph/.avn/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/Users/steph/.avn/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/steph/.avn/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/steph/.avn/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/steph/.avn/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/steph/.avn/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/steph/.avn/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/steph/.avn/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/steph/.avn/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/steph/.avn/node_modules/bluebird/js/release/async.js:15:14)
```

Thank you

**Comment by wbyoung** [comment]
Uninstall `avn-nvm` or create a JSON file at `~/.avnrc` with the key `plugins` that's an array of the names of the plugins you want used in the order you want them used. See [this file](https://github.com/wbyoung/avn/blob/master/lib/setup/config.js).
